/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini.project;

import java.util.LinkedList;
import java.util.List;
import mini.project.domain.Book;
import mini.project.domain.Member;
import mini.project.handler.BookHandler;
import mini.project.handler.MemberHandler;
import mini.project.util.Prompt;

public class App {

  public static void main(String[] args) {

    List<Member> memberList = new LinkedList<>();
    MemberHandler memberHandler = new MemberHandler(memberList);

    List<Book> bookList = new LinkedList<>();
    BookHandler bookHandler = new BookHandler(bookList, memberHandler);


    System.out.println("안녕하십니까? \n비트도서관 대여관리 시스템 입니다.");
    System.out.println();
    loop:
      while (true) {
        System.out.println("1: 회원가입, 2: 회원목록 , 3: 회원상세조회, 4: 회원정보수정\n"
            + "5: 도서대여 , 6: 대여도서정보 , 9: 회원탈퇴, 0: 종료");
        
        String command = Prompt.inputString("명령을 입력하세요. > ");


        switch (command) {
          case "1": memberHandler.add(); break;
          case "2": memberHandler.list(); break;
          case "3": memberHandler.detail(); break;
          case "4": memberHandler.update(); break;
          case "5": bookHandler.add(); break;
          case "6": bookHandler.list(); break;
          case "9": memberHandler.delete(); break;
          case "10": memberHandler.searchId(); break;
          case "11": memberHandler.searchPassword(); break;

          case "0" :
            System.out.println("이용해 주셔서 감사합니다.");
            break loop;
          default:
            System.out.println("존재하지 않는 명령입니다.\n다시 입력해주세요.");
        }
        System.out.println();
      }
    Prompt.close();
  }
}
